apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: spring-test-ts
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: spring-test-ts 
  name: spring-test-ts
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: spring-test-ts
    weight: 100 
